from sqlalchemy import ARRAY
from . import db
from flask_login import UserMixin

class Lineup(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    lineup_name = db.Column(db.String(100))
    player1id = db.Column(db.Integer)
    player2id = db.Column(db.Integer)
    player3id = db.Column(db.Integer)
    player4id = db.Column(db.Integer)
    player5id = db.Column(db.Integer)
    player6id = db.Column(db.Integer)
    player7id = db.Column(db.Integer)
    player8id = db.Column(db.Integer)
    player9id = db.Column(db.Integer)
    score = db.Column(db.Float)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id')) 

class Player(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    player = db.Column(db.String(150))
    season = db.Column(db.String(4))
    pos = db.Column(db.String(2))
    age = db.Column(db.Integer)
    team = db.Column(db.String(15))
    g = db.Column(db.Integer)
    pa = db.Column(db.Integer)
    ab = db.Column(db.Integer)
    r = db.Column(db.Integer)
    h = db.Column(db.Integer)
    twoB = db.Column(db.Integer)
    threeB = db.Column(db.Integer)
    hr = db.Column(db.Integer)
    rbi = db.Column(db.Integer)
    sb = db.Column(db.Integer)
    cs = db.Column(db.Integer)
    bb = db.Column(db.Integer)
    so = db.Column(db.Integer)
    ba = db.Column(db.Float)
    obp = db.Column(db.Float)
    slg = db.Column(db.Float)
    ops = db.Column(db.Float)
    opsPlus = db.Column(db.Integer)
    tb = db.Column(db.Integer)
    gdp = db.Column(db.Integer)
    hbp = db.Column(db.Integer)
    sh = db.Column(db.Integer)
    sf = db.Column(db.Integer)
    ibb = db.Column(db.Integer)
    spf = db.Column(db.Integer)
    isCustom = db.Column(db.Boolean, default=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=True)

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    name = db.Column(db.String(150))
    numLineups = db.Column(db.Integer, default = 0)
    numCustomPlayers = db.Column(db.Integer, default = 0)
    lineups = db.relationship('Lineup', backref='user')