from . import db
from flask_login import UserMixin

class Lineup(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    lineup_name = db.Column(db.String(25))
    player1id = db.Column(db.Integer)
    player2id = db.Column(db.Integer)
    player3id = db.Column(db.Integer)
    player4id = db.Column(db.Integer)
    player5id = db.Column(db.Integer)
    player6id = db.Column(db.Integer)
    player7id = db.Column(db.Integer)
    player8id = db.Column(db.Integer)
    player9id = db.Column(db.Integer)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class Player(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    player = db.Column(db.String(150))
    season = db.Column(db.String(4))
    team = db.Column(db.String(10))
    pa = db.Column(db.Integer)
    ab = db.Column(db.Integer)
    h = db.Column(db.Integer)
    twoB = db.Column(db.Integer)
    threeB = db.Column(db.Integer)
    hr = db.Column(db.Integer)
    bb = db.Column(db.Integer)
    so = db.Column(db.Integer)
    ba = db.Column(db.Float)
    obp = db.Column(db.Float)
    slg = db.Column(db.Float)
    woba = db.Column(db.Float)
    wobacon = db.Column(db.Float)
    pitches = db.Column(db.Integer)
    batted_balls = db.Column(db.Integer)
    barrels = db.Column(db.Integer)
    barrel_percentage = db.Column(db.Float)
    hard_hit_percentage = db.Column(db.Float)
    exit_velocity = db.Column(db.Float)
    launch_angle = db.Column(db.Float)
    xba = db.Column(db.Float)
    xslg = db.Column(db.Float)
    xwoba = db.Column(db.Float)
    xwobacon = db.Column(db.Float)

class CustomPlayer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    player = db.Column(db.String(150))
    season = db.Column(db.String(4))
    pa = db.Column(db.Integer)
    ab = db.Column(db.Integer)
    h = db.Column(db.Integer)
    twoB = db.Column(db.Integer)
    threeB = db.Column(db.Integer)
    hr = db.Column(db.Integer)
    bb = db.Column(db.Integer)
    so = db.Column(db.Integer)
    ba = db.Column(db.Float)
    obp = db.Column(db.Float)
    slg = db.Column(db.Float)
    woba = db.Column(db.Float)
    wobacon = db.Column(db.Float)
    pitches = db.Column(db.Integer)
    batted_balls = db.Column(db.Integer)
    barrels = db.Column(db.Integer)
    barrel_percentage = db.Column(db.Float)
    hard_hit_percentage = db.Column(db.Float)
    exit_velocity = db.Column(db.Float)
    launch_angle = db.Column(db.Float)
    xba = db.Column(db.Float)
    xslg = db.Column(db.Float)
    xwoba = db.Column(db.Float)
    xwobacon = db.Column(db.Float)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    name = db.Column(db.String(150))
    lineups = db.relationship('Lineup')
    custom_players = db.relationship('CustomPlayer')